apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sftpgo-credentials
  namespace: sftpgo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  target:
    name: sftpgo-credentials
    creationPolicy: Owner
  data:
    - secretKey: admin-username
      remoteRef:
        key: SFTPGO_ADMIN_USERNAME
    - secretKey: admin-password
      remoteRef:
        key: SFTPGO_ADMIN_PASSWORD
