apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: marketing-automation-secrets
  namespace: marketing-automation
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  target:
    name: marketing-automation-secrets
    creationPolicy: Owner
  data:
    - secretKey: auth-user
      remoteRef:
        key: MARKETING_AUTOMATION_AUTH_USER
    - secretKey: auth-pass
      remoteRef:
        key: MARKETING_AUTOMATION_AUTH_PASS
