apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-metadata
  namespace: airflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  target:
    name: airflow-metadata
    creationPolicy: Owner
    template:
      data:
        connection: "postgresql+psycopg2://postgres:{{ .postgres_password }}@postgres.postgres.svc.cluster.local:5432/airflow"
  data:
    - secretKey: postgres_password
      remoteRef:
        key: POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-metadata-connection
  namespace: airflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  target:
    name: airflow-metadata-connection
    creationPolicy: Owner
    template:
      data:
        connection: "postgresql+psycopg2://postgres:{{ .postgres_password }}@postgres.postgres.svc.cluster.local:5432/airflow"
  data:
    - secretKey: postgres_password
      remoteRef:
        key: POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-fernet-key
  namespace: airflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  target:
    name: airflow-fernet-key
    creationPolicy: Owner
  data:
    - secretKey: fernet-key
      remoteRef:
        key: AIRFLOW_FERNET_KEY
