apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-store
spec:
  provider:
    infisical:
      hostAPI: https://app.infisical.com
      auth:
        universalAuthCredentials:
          # NOTE: This secret "infisical-universal-auth" must be manually created.
          # kubectl create secret generic infisical-universal-auth \
          # --namespace external-secrets \
          # --from-literal=clientId=YOUR_ID \
          # --from-literal=clientSecret=YOUR_SECRET
          clientId:
            name: infisical-universal-auth
            namespace: external-secrets
            key: clientId
          clientSecret:
            name: infisical-universal-auth
            namespace: external-secrets
            key: clientSecret
      secretsScope:
        projectSlug: homelab-t5-do
        environmentSlug: dev
