apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-creds
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  target:
    name: ghcr-creds
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: helm
        url: oci://ghcr.io/go-vikunja/helm-chart/vikunja
        username: "{{ .username }}"
        password: "{{ .token }}"
        enableOCI: "true"
  data:
    - secretKey: username
      remoteRef:
        key: GITHUB_USERNAME
    - secretKey: token
      remoteRef:
        key: GITHUB_TOKEN
