apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-creds
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  target:
    name: github-creds
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        type: git
        url: https://github.com/Danavira
        username: "{{ .username }}"
        password: "{{ .token }}"
  data:
    - secretKey: username
      remoteRef:
        key: GITHUB_USERNAME
    - secretKey: token
      remoteRef:
        key: GITHUB_TOKEN
