apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-image-updater-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  target:
    name: argocd-image-updater-secret
    creationPolicy: Owner
    template:
      data:
        argocd.token: ""
        git.token: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: GITHUB_TOKEN
